#!/bin/bash
# ================================================
# ZSH->DLDC ======================================
# ================================================
source .env

export UID

# ------------------------------------------------
# DETERMINE-COMMAND ------------------------------
# ------------------------------------------------

# Default to up, allow "" for up, handle "down", handle 
# additional arguments to docker-compose <command> ...
_command="up"

case $1 in
  "")
    ;;
  up)
    shift
    ;;
  shell)
    _container_id=`nvidia-docker ps -aqf "name=dldc_jupyter"`

    if [[ -n $_container_id ]] ; then
      echo "Opening shell on running container ${_container_id}..."
      nvidia-docker exec -it $_container_id bash
    else
      echo "Opening shell on new container..."
      nvidia-docker run -it dldc bash
    fi

    exit
    ;;
  *)
    _command="$1"
    shift
    ;;
esac

# ------------------------------------------------
# HANDLE-UP --------------------------------------
# ------------------------------------------------
if [[ $_command == "up" ]] ; then

  if [ -z $EXTERNAL_HOST ] ; then
    echo "EXTERNAL_HOST is not set. Using system hostname '$HOST'"
    export EXTERNAL_HOST=$HOST
  else
    echo "Using host: $EXTERNAL_HOST"
  fi

  # Make sure we're down
  echo "Ensuring services are down..."
  nvidia-docker-compose down --remove-orphans

  # Always build
  docker build --tag dldc .
fi

# Issue main compose command
# ------------------------------------------------
nvidia-docker-compose $_command $*
